name: MatematicaWM
description: "Infinite Math Game"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  states_rebuilder: ^6.3.0
  prefs: ^4.1.0+3
  one_context: ^4.0.0
  dynamic_color: ^1.6.9
  google_fonts: ^6.1.0
  auto_size_text: ^3.0.0
  flutter_screen_scaler: ^2.1.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  rename_app: ^1.3.2
  flutter_launcher_icons: ^0.14.1

flutter:

  uses-material-design: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "icon.png"